#!/bin/sh
#
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# * This file is part of SableCC.                             *
# * See the file "LICENSE" for copyright information and the  *
# * terms and conditions for copying, distribution and        *
# * modification of SableCC.                                  *
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#
# IMPORTANT: Put the absolute path to sablecc.jar below.
java -jar  ~/Google_Drive/AAU/4._Semester/P4/src/P4/sablecc.jar GCL.sable $*
mv ~/Google_Drive/AAU/4._Semester/P4/src/P4/P4/Sable ~/Google_Drive/AAU/4._Semester/P4/src/P4/Sable $*
rm -r ~/Google_Drive/AAU/4._Semester/P4/src/P4/P4 $*