/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.analysis;

import java.util.*;
import P4.Sable.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProg(AProg node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIncludes(AIncludes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASetup(ASetup node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACard(ACard node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClassBody(AClassBody node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubclass(ASubclass node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPublic(APublic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrivate(APrivate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoves(AMoves node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADcl(ADcl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleDcl(ASingleDcl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADclList(ADclList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInit(AInit node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandExpr(AExpandExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleExpr(ASingleExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandEquality(AExpandEquality node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleEquality(ASingleEquality node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandRelation(AExpandRelation node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleRelation(ASingleRelation node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandAddExpr(AExpandAddExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleAddExpr(ASingleAddExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandTerm(AExpandTerm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFactorTerm(AFactorTerm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandFactor(AExpandFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALiteralFactor(ALiteralFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValFactor(AValFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInitFactor(AInitFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParens(AParens node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntLiteral(AIntLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFloatLiteral(AFloatLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringLiteral(AStringLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolLiteral(ABoolLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElementList(AElementList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandElement(AExpandElement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASingleElement(ASingleElement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVal(AVal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValList(AValList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACall(ACall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParamList(AParamList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParam(AParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMethodDcl(AMethodDcl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParamDclList(AParamDclList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpandParam(AExpandParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParamDcl(AParamDcl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAType(AType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAList(AList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAReturnStmt(AReturnStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASelectStmt(ASelectStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADclStmt(ADclStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALoopStmt(ALoopStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignStmt(AAssignStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACallStmt(ACallStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfSelectStmt(AIfSelectStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASwitchSelectStmt(ASwitchSelectStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlock(ABlock node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfStmt(AIfStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElseIf(AElseIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElseStmt(AElseStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASwitchStmt(ASwitchStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACase(ACase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaseCaseStmt(ACaseCaseStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADefaultCaseStmt(ADefaultCaseStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWhileLoopStmt(AWhileLoopStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAForLoopStmt(AForLoopStmt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWhileLoop(AWhileLoop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAForLoop(AForLoop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAForeachLoopExpr(AForeachLoopExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAForLoopExpr(AForLoopExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclareInitLoop(ADeclareInitLoop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignInitLoop(AAssignInitLoop node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignValue(AAssignValue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATurn(ATurn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEndCon(AEndCon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnd(AEnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBoolLiteral(TBoolLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAddOp(TAddOp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMultOp(TMultOp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIntLiteral(TIntLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFloatLiteral(TFloatLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBoolOp(TBoolOp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRelationOp(TRelationOp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssign(TAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEqualOp(TEqualOp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLParen(TLParen node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRParen(TRParen node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrack(TLBrack node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrack(TRBrack node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSetup(TSetup node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPublic(TPublic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrivate(TPrivate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeparator(TSeparator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDot(TDot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMoves(TMoves node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBox(TLBox node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBox(TRBox node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTReturn(TReturn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemi(TSemi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSwitch(TSwitch node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCase(TCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDefault(TDefault node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhile(TWhile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFor(TFor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTForeach(TForeach node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTurn(TTurn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEndCon(TEndCon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCard(TCard node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLArr(TLArr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRArr(TRArr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTList(TList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTypeof(TTypeof node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFun(TFun node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInc(TInc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSub(TSub node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
