/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.analysis;

import java.util.*;
import P4.Sable.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProg().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProg(AProg node)
    {
        defaultIn(node);
    }

    public void outAProg(AProg node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProg(AProg node)
    {
        inAProg(node);
        if(node.getSetup() != null)
        {
            node.getSetup().apply(this);
        }
        if(node.getMoves() != null)
        {
            node.getMoves().apply(this);
        }
        if(node.getTurn() != null)
        {
            node.getTurn().apply(this);
        }
        if(node.getEndCon() != null)
        {
            node.getEndCon().apply(this);
        }
        if(node.getMoveDclList() != null)
        {
            node.getMoveDclList().apply(this);
        }
        outAProg(node);
    }

    public void inASetup(ASetup node)
    {
        defaultIn(node);
    }

    public void outASetup(ASetup node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASetup(ASetup node)
    {
        inASetup(node);
        if(node.getSetup() != null)
        {
            node.getSetup().apply(this);
        }
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getStmtList() != null)
        {
            node.getStmtList().apply(this);
        }
        if(node.getPublic() != null)
        {
            node.getPublic().apply(this);
        }
        if(node.getPrivate() != null)
        {
            node.getPrivate().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outASetup(node);
    }

    public void inAPublic(APublic node)
    {
        defaultIn(node);
    }

    public void outAPublic(APublic node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPublic(APublic node)
    {
        inAPublic(node);
        if(node.getPublic() != null)
        {
            node.getPublic().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAPublic(node);
    }

    public void inAPrivate(APrivate node)
    {
        defaultIn(node);
    }

    public void outAPrivate(APrivate node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrivate(APrivate node)
    {
        inAPrivate(node);
        if(node.getPrivate() != null)
        {
            node.getPrivate().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAPrivate(node);
    }

    public void inAMoves(AMoves node)
    {
        defaultIn(node);
    }

    public void outAMoves(AMoves node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMoves(AMoves node)
    {
        inAMoves(node);
        if(node.getMoves() != null)
        {
            node.getMoves().apply(this);
        }
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getMoveDclList() != null)
        {
            node.getMoveDclList().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outAMoves(node);
    }

    public void inAExpandDclList(AExpandDclList node)
    {
        defaultIn(node);
    }

    public void outAExpandDclList(AExpandDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandDclList(AExpandDclList node)
    {
        inAExpandDclList(node);
        if(node.getDclPre() != null)
        {
            node.getDclPre().apply(this);
        }
        if(node.getSeparator() != null)
        {
            node.getSeparator().apply(this);
        }
        if(node.getDclList() != null)
        {
            node.getDclList().apply(this);
        }
        outAExpandDclList(node);
    }

    public void inASingleDclList(ASingleDclList node)
    {
        defaultIn(node);
    }

    public void outASingleDclList(ASingleDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleDclList(ASingleDclList node)
    {
        inASingleDclList(node);
        if(node.getDclPre() != null)
        {
            node.getDclPre().apply(this);
        }
        outASingleDclList(node);
    }

    public void inADcl(ADcl node)
    {
        defaultIn(node);
    }

    public void outADcl(ADcl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADcl(ADcl node)
    {
        inADcl(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getDclList() != null)
        {
            node.getDclList().apply(this);
        }
        outADcl(node);
    }

    public void inADclPre(ADclPre node)
    {
        defaultIn(node);
    }

    public void outADclPre(ADclPre node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADclPre(ADclPre node)
    {
        inADclPre(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInit() != null)
        {
            node.getInit().apply(this);
        }
        outADclPre(node);
    }

    public void inAValueInit(AValueInit node)
    {
        defaultIn(node);
    }

    public void outAValueInit(AValueInit node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValueInit(AValueInit node)
    {
        inAValueInit(node);
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAValueInit(node);
    }

    public void inAEmptyInit(AEmptyInit node)
    {
        defaultIn(node);
    }

    public void outAEmptyInit(AEmptyInit node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyInit(AEmptyInit node)
    {
        inAEmptyInit(node);
        outAEmptyInit(node);
    }

    public void inAExpandExpr(AExpandExpr node)
    {
        defaultIn(node);
    }

    public void outAExpandExpr(AExpandExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandExpr(AExpandExpr node)
    {
        inAExpandExpr(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getBoolOp() != null)
        {
            node.getBoolOp().apply(this);
        }
        if(node.getEquality() != null)
        {
            node.getEquality().apply(this);
        }
        outAExpandExpr(node);
    }

    public void inASingleExpr(ASingleExpr node)
    {
        defaultIn(node);
    }

    public void outASingleExpr(ASingleExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleExpr(ASingleExpr node)
    {
        inASingleExpr(node);
        if(node.getEquality() != null)
        {
            node.getEquality().apply(this);
        }
        outASingleExpr(node);
    }

    public void inAExpandEquality(AExpandEquality node)
    {
        defaultIn(node);
    }

    public void outAExpandEquality(AExpandEquality node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandEquality(AExpandEquality node)
    {
        inAExpandEquality(node);
        if(node.getEquality() != null)
        {
            node.getEquality().apply(this);
        }
        if(node.getEqualOp() != null)
        {
            node.getEqualOp().apply(this);
        }
        if(node.getRelation() != null)
        {
            node.getRelation().apply(this);
        }
        outAExpandEquality(node);
    }

    public void inASingleEquality(ASingleEquality node)
    {
        defaultIn(node);
    }

    public void outASingleEquality(ASingleEquality node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleEquality(ASingleEquality node)
    {
        inASingleEquality(node);
        if(node.getRelation() != null)
        {
            node.getRelation().apply(this);
        }
        outASingleEquality(node);
    }

    public void inAExpandRelation(AExpandRelation node)
    {
        defaultIn(node);
    }

    public void outAExpandRelation(AExpandRelation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandRelation(AExpandRelation node)
    {
        inAExpandRelation(node);
        if(node.getRelation() != null)
        {
            node.getRelation().apply(this);
        }
        if(node.getRelationOp() != null)
        {
            node.getRelationOp().apply(this);
        }
        if(node.getAddExpr() != null)
        {
            node.getAddExpr().apply(this);
        }
        outAExpandRelation(node);
    }

    public void inASingleRelation(ASingleRelation node)
    {
        defaultIn(node);
    }

    public void outASingleRelation(ASingleRelation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleRelation(ASingleRelation node)
    {
        inASingleRelation(node);
        if(node.getAddExpr() != null)
        {
            node.getAddExpr().apply(this);
        }
        outASingleRelation(node);
    }

    public void inAExpandAddExpr(AExpandAddExpr node)
    {
        defaultIn(node);
    }

    public void outAExpandAddExpr(AExpandAddExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandAddExpr(AExpandAddExpr node)
    {
        inAExpandAddExpr(node);
        if(node.getAddExpr() != null)
        {
            node.getAddExpr().apply(this);
        }
        if(node.getAddOp() != null)
        {
            node.getAddOp().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAExpandAddExpr(node);
    }

    public void inASingleAddExpr(ASingleAddExpr node)
    {
        defaultIn(node);
    }

    public void outASingleAddExpr(ASingleAddExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleAddExpr(ASingleAddExpr node)
    {
        inASingleAddExpr(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outASingleAddExpr(node);
    }

    public void inAExpandTerm(AExpandTerm node)
    {
        defaultIn(node);
    }

    public void outAExpandTerm(AExpandTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandTerm(AExpandTerm node)
    {
        inAExpandTerm(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMultOp() != null)
        {
            node.getMultOp().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAExpandTerm(node);
    }

    public void inAFactorTerm(AFactorTerm node)
    {
        defaultIn(node);
    }

    public void outAFactorTerm(AFactorTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorTerm(AFactorTerm node)
    {
        inAFactorTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorTerm(node);
    }

    public void inAExpandFactor(AExpandFactor node)
    {
        defaultIn(node);
    }

    public void outAExpandFactor(AExpandFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandFactor(AExpandFactor node)
    {
        inAExpandFactor(node);
        if(node.getParens() != null)
        {
            node.getParens().apply(this);
        }
        outAExpandFactor(node);
    }

    public void inALiteralFactor(ALiteralFactor node)
    {
        defaultIn(node);
    }

    public void outALiteralFactor(ALiteralFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALiteralFactor(ALiteralFactor node)
    {
        inALiteralFactor(node);
        if(node.getLiteral() != null)
        {
            node.getLiteral().apply(this);
        }
        outALiteralFactor(node);
    }

    public void inAValFactor(AValFactor node)
    {
        defaultIn(node);
    }

    public void outAValFactor(AValFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValFactor(AValFactor node)
    {
        inAValFactor(node);
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        outAValFactor(node);
    }

    public void inAInitFactor(AInitFactor node)
    {
        defaultIn(node);
    }

    public void outAInitFactor(AInitFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInitFactor(AInitFactor node)
    {
        inAInitFactor(node);
        if(node.getInitList() != null)
        {
            node.getInitList().apply(this);
        }
        outAInitFactor(node);
    }

    public void inAParens(AParens node)
    {
        defaultIn(node);
    }

    public void outAParens(AParens node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParens(AParens node)
    {
        inAParens(node);
        if(node.getLParen() != null)
        {
            node.getLParen().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getRParen() != null)
        {
            node.getRParen().apply(this);
        }
        outAParens(node);
    }

    public void inAIntLiteral(AIntLiteral node)
    {
        defaultIn(node);
    }

    public void outAIntLiteral(AIntLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntLiteral(AIntLiteral node)
    {
        inAIntLiteral(node);
        if(node.getIntLiteral() != null)
        {
            node.getIntLiteral().apply(this);
        }
        outAIntLiteral(node);
    }

    public void inAFloatLiteral(AFloatLiteral node)
    {
        defaultIn(node);
    }

    public void outAFloatLiteral(AFloatLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFloatLiteral(AFloatLiteral node)
    {
        inAFloatLiteral(node);
        if(node.getFloatLiteral() != null)
        {
            node.getFloatLiteral().apply(this);
        }
        outAFloatLiteral(node);
    }

    public void inAStringLiteral(AStringLiteral node)
    {
        defaultIn(node);
    }

    public void outAStringLiteral(AStringLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringLiteral(AStringLiteral node)
    {
        inAStringLiteral(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringLiteral(node);
    }

    public void inABoolLiteral(ABoolLiteral node)
    {
        defaultIn(node);
    }

    public void outABoolLiteral(ABoolLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolLiteral(ABoolLiteral node)
    {
        inABoolLiteral(node);
        if(node.getBoolLiteral() != null)
        {
            node.getBoolLiteral().apply(this);
        }
        outABoolLiteral(node);
    }

    public void inAInitList(AInitList node)
    {
        defaultIn(node);
    }

    public void outAInitList(AInitList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInitList(AInitList node)
    {
        inAInitList(node);
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getElementList() != null)
        {
            node.getElementList().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outAInitList(node);
    }

    public void inAExpandElementList(AExpandElementList node)
    {
        defaultIn(node);
    }

    public void outAExpandElementList(AExpandElementList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandElementList(AExpandElementList node)
    {
        inAExpandElementList(node);
        if(node.getElement() != null)
        {
            node.getElement().apply(this);
        }
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getElementList() != null)
        {
            node.getElementList().apply(this);
        }
        outAExpandElementList(node);
    }

    public void inAEmptyElementList(AEmptyElementList node)
    {
        defaultIn(node);
    }

    public void outAEmptyElementList(AEmptyElementList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyElementList(AEmptyElementList node)
    {
        inAEmptyElementList(node);
        outAEmptyElementList(node);
    }

    public void inAExpandElement(AExpandElement node)
    {
        defaultIn(node);
    }

    public void outAExpandElement(AExpandElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandElement(AExpandElement node)
    {
        inAExpandElement(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getSeparator() != null)
        {
            node.getSeparator().apply(this);
        }
        if(node.getElement() != null)
        {
            node.getElement().apply(this);
        }
        outAExpandElement(node);
    }

    public void inASingleElement(ASingleElement node)
    {
        defaultIn(node);
    }

    public void outASingleElement(ASingleElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleElement(ASingleElement node)
    {
        inASingleElement(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outASingleElement(node);
    }

    public void inAVal(AVal node)
    {
        defaultIn(node);
    }

    public void outAVal(AVal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVal(AVal node)
    {
        inAVal(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCall() != null)
        {
            node.getCall().apply(this);
        }
        if(node.getValList() != null)
        {
            node.getValList().apply(this);
        }
        outAVal(node);
    }

    public void inAExpandValList(AExpandValList node)
    {
        defaultIn(node);
    }

    public void outAExpandValList(AExpandValList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandValList(AExpandValList node)
    {
        inAExpandValList(node);
        if(node.getDot() != null)
        {
            node.getDot().apply(this);
        }
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        outAExpandValList(node);
    }

    public void inAEmptyValList(AEmptyValList node)
    {
        defaultIn(node);
    }

    public void outAEmptyValList(AEmptyValList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyValList(AEmptyValList node)
    {
        inAEmptyValList(node);
        outAEmptyValList(node);
    }

    public void inACallCall(ACallCall node)
    {
        defaultIn(node);
    }

    public void outACallCall(ACallCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallCall(ACallCall node)
    {
        inACallCall(node);
        if(node.getParamList() != null)
        {
            node.getParamList().apply(this);
        }
        outACallCall(node);
    }

    public void inAEmptyCall(AEmptyCall node)
    {
        defaultIn(node);
    }

    public void outAEmptyCall(AEmptyCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyCall(AEmptyCall node)
    {
        inAEmptyCall(node);
        outAEmptyCall(node);
    }

    public void inAParamList(AParamList node)
    {
        defaultIn(node);
    }

    public void outAParamList(AParamList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamList(AParamList node)
    {
        inAParamList(node);
        if(node.getLParen() != null)
        {
            node.getLParen().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        {
            List<PParam> copy = new ArrayList<PParam>(node.getParam());
            for(PParam e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRParen() != null)
        {
            node.getRParen().apply(this);
        }
        outAParamList(node);
    }

    public void inAParam(AParam node)
    {
        defaultIn(node);
    }

    public void outAParam(AParam node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParam(AParam node)
    {
        inAParam(node);
        if(node.getSeparator() != null)
        {
            node.getSeparator().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAParam(node);
    }

    public void inAExpandMoveDclList(AExpandMoveDclList node)
    {
        defaultIn(node);
    }

    public void outAExpandMoveDclList(AExpandMoveDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandMoveDclList(AExpandMoveDclList node)
    {
        inAExpandMoveDclList(node);
        if(node.getMethodDcl() != null)
        {
            node.getMethodDcl().apply(this);
        }
        if(node.getMoveDclList() != null)
        {
            node.getMoveDclList().apply(this);
        }
        outAExpandMoveDclList(node);
    }

    public void inAEmptyMoveDclList(AEmptyMoveDclList node)
    {
        defaultIn(node);
    }

    public void outAEmptyMoveDclList(AEmptyMoveDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyMoveDclList(AEmptyMoveDclList node)
    {
        inAEmptyMoveDclList(node);
        outAEmptyMoveDclList(node);
    }

    public void inAMethodDcl(AMethodDcl node)
    {
        defaultIn(node);
    }

    public void outAMethodDcl(AMethodDcl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodDcl(AMethodDcl node)
    {
        inAMethodDcl(node);
        if(node.getFun() != null)
        {
            node.getFun().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getLParen() != null)
        {
            node.getLParen().apply(this);
        }
        if(node.getParamDclList() != null)
        {
            node.getParamDclList().apply(this);
        }
        if(node.getRParen() != null)
        {
            node.getRParen().apply(this);
        }
        if(node.getTypeof() != null)
        {
            node.getTypeof().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getStmtList() != null)
        {
            node.getStmtList().apply(this);
        }
        if(node.getReturnStmt() != null)
        {
            node.getReturnStmt().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outAMethodDcl(node);
    }

    public void inAExpandParamDclList(AExpandParamDclList node)
    {
        defaultIn(node);
    }

    public void outAExpandParamDclList(AExpandParamDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandParamDclList(AExpandParamDclList node)
    {
        inAExpandParamDclList(node);
        if(node.getParamDcl() != null)
        {
            node.getParamDcl().apply(this);
        }
        if(node.getSeparator() != null)
        {
            node.getSeparator().apply(this);
        }
        if(node.getParamDclList() != null)
        {
            node.getParamDclList().apply(this);
        }
        outAExpandParamDclList(node);
    }

    public void inASingleParamDclList(ASingleParamDclList node)
    {
        defaultIn(node);
    }

    public void outASingleParamDclList(ASingleParamDclList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleParamDclList(ASingleParamDclList node)
    {
        inASingleParamDclList(node);
        if(node.getParamDcl() != null)
        {
            node.getParamDcl().apply(this);
        }
        outASingleParamDclList(node);
    }

    public void inASingleParamDcl(ASingleParamDcl node)
    {
        defaultIn(node);
    }

    public void outASingleParamDcl(ASingleParamDcl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleParamDcl(ASingleParamDcl node)
    {
        inASingleParamDcl(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outASingleParamDcl(node);
    }

    public void inAEmptyParamDcl(AEmptyParamDcl node)
    {
        defaultIn(node);
    }

    public void outAEmptyParamDcl(AEmptyParamDcl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyParamDcl(AEmptyParamDcl node)
    {
        inAEmptyParamDcl(node);
        outAEmptyParamDcl(node);
    }

    public void inATypeType(ATypeType node)
    {
        defaultIn(node);
    }

    public void outATypeType(ATypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATypeType(ATypeType node)
    {
        inATypeType(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outATypeType(node);
    }

    public void inAListType(AListType node)
    {
        defaultIn(node);
    }

    public void outAListType(AListType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListType(AListType node)
    {
        inAListType(node);
        if(node.getList() != null)
        {
            node.getList().apply(this);
        }
        outAListType(node);
    }

    public void inAList(AList node)
    {
        defaultIn(node);
    }

    public void outAList(AList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAList(AList node)
    {
        inAList(node);
        if(node.getList() != null)
        {
            node.getList().apply(this);
        }
        if(node.getTypeof() != null)
        {
            node.getTypeof().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAList(node);
    }

    public void inAExpandStmtList(AExpandStmtList node)
    {
        defaultIn(node);
    }

    public void outAExpandStmtList(AExpandStmtList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpandStmtList(AExpandStmtList node)
    {
        inAExpandStmtList(node);
        if(node.getStmt() != null)
        {
            node.getStmt().apply(this);
        }
        if(node.getStmtList() != null)
        {
            node.getStmtList().apply(this);
        }
        outAExpandStmtList(node);
    }

    public void inAEmptyStmtList(AEmptyStmtList node)
    {
        defaultIn(node);
    }

    public void outAEmptyStmtList(AEmptyStmtList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyStmtList(AEmptyStmtList node)
    {
        inAEmptyStmtList(node);
        outAEmptyStmtList(node);
    }

    public void inASingleReturnStmt(ASingleReturnStmt node)
    {
        defaultIn(node);
    }

    public void outASingleReturnStmt(ASingleReturnStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleReturnStmt(ASingleReturnStmt node)
    {
        inASingleReturnStmt(node);
        if(node.getReturn() != null)
        {
            node.getReturn().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        outASingleReturnStmt(node);
    }

    public void inAEmptyReturnStmt(AEmptyReturnStmt node)
    {
        defaultIn(node);
    }

    public void outAEmptyReturnStmt(AEmptyReturnStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyReturnStmt(AEmptyReturnStmt node)
    {
        inAEmptyReturnStmt(node);
        outAEmptyReturnStmt(node);
    }

    public void inASelectStmt(ASelectStmt node)
    {
        defaultIn(node);
    }

    public void outASelectStmt(ASelectStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASelectStmt(ASelectStmt node)
    {
        inASelectStmt(node);
        if(node.getSelectStmt() != null)
        {
            node.getSelectStmt().apply(this);
        }
        outASelectStmt(node);
    }

    public void inADclStmt(ADclStmt node)
    {
        defaultIn(node);
    }

    public void outADclStmt(ADclStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADclStmt(ADclStmt node)
    {
        inADclStmt(node);
        if(node.getDcl() != null)
        {
            node.getDcl().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        outADclStmt(node);
    }

    public void inALoopStmt(ALoopStmt node)
    {
        defaultIn(node);
    }

    public void outALoopStmt(ALoopStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALoopStmt(ALoopStmt node)
    {
        inALoopStmt(node);
        if(node.getLoopStmt() != null)
        {
            node.getLoopStmt().apply(this);
        }
        outALoopStmt(node);
    }

    public void inAAssignStmt(AAssignStmt node)
    {
        defaultIn(node);
    }

    public void outAAssignStmt(AAssignStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignStmt(AAssignStmt node)
    {
        inAAssignStmt(node);
        if(node.getAssignValue() != null)
        {
            node.getAssignValue().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        outAAssignStmt(node);
    }

    public void inACallStmt(ACallStmt node)
    {
        defaultIn(node);
    }

    public void outACallStmt(ACallStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallStmt(ACallStmt node)
    {
        inACallStmt(node);
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        outACallStmt(node);
    }

    public void inAIfSelectStmt(AIfSelectStmt node)
    {
        defaultIn(node);
    }

    public void outAIfSelectStmt(AIfSelectStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfSelectStmt(AIfSelectStmt node)
    {
        inAIfSelectStmt(node);
        if(node.getIfStmt() != null)
        {
            node.getIfStmt().apply(this);
        }
        outAIfSelectStmt(node);
    }

    public void inASwitchSelectStmt(ASwitchSelectStmt node)
    {
        defaultIn(node);
    }

    public void outASwitchSelectStmt(ASwitchSelectStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASwitchSelectStmt(ASwitchSelectStmt node)
    {
        inASwitchSelectStmt(node);
        if(node.getSwitchStmt() != null)
        {
            node.getSwitchStmt().apply(this);
        }
        outASwitchSelectStmt(node);
    }

    public void inABlock(ABlock node)
    {
        defaultIn(node);
    }

    public void outABlock(ABlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlock(ABlock node)
    {
        inABlock(node);
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getStmtList() != null)
        {
            node.getStmtList().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outABlock(node);
    }

    public void inAIfStmt(AIfStmt node)
    {
        defaultIn(node);
    }

    public void outAIfStmt(AIfStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfStmt(AIfStmt node)
    {
        inAIfStmt(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getElseStmt() != null)
        {
            node.getElseStmt().apply(this);
        }
        outAIfStmt(node);
    }

    public void inAElseifElseStmt(AElseifElseStmt node)
    {
        defaultIn(node);
    }

    public void outAElseifElseStmt(AElseifElseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseifElseStmt(AElseifElseStmt node)
    {
        inAElseifElseStmt(node);
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getIfStmt() != null)
        {
            node.getIfStmt().apply(this);
        }
        outAElseifElseStmt(node);
    }

    public void inAElseElseStmt(AElseElseStmt node)
    {
        defaultIn(node);
    }

    public void outAElseElseStmt(AElseElseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseElseStmt(AElseElseStmt node)
    {
        inAElseElseStmt(node);
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAElseElseStmt(node);
    }

    public void inAElseStmt(AElseStmt node)
    {
        defaultIn(node);
    }

    public void outAElseStmt(AElseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseStmt(AElseStmt node)
    {
        inAElseStmt(node);
        outAElseStmt(node);
    }

    public void inASwitchStmt(ASwitchStmt node)
    {
        defaultIn(node);
    }

    public void outASwitchStmt(ASwitchStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASwitchStmt(ASwitchStmt node)
    {
        inASwitchStmt(node);
        if(node.getSwitch() != null)
        {
            node.getSwitch().apply(this);
        }
        if(node.getLParen() != null)
        {
            node.getLParen().apply(this);
        }
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getCaseList() != null)
        {
            node.getCaseList().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outASwitchStmt(node);
    }

    public void inAListCaseList(AListCaseList node)
    {
        defaultIn(node);
    }

    public void outAListCaseList(AListCaseList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListCaseList(AListCaseList node)
    {
        inAListCaseList(node);
        if(node.getCaseStmt() != null)
        {
            node.getCaseStmt().apply(this);
        }
        if(node.getCaseList() != null)
        {
            node.getCaseList().apply(this);
        }
        outAListCaseList(node);
    }

    public void inADefaultCaseList(ADefaultCaseList node)
    {
        defaultIn(node);
    }

    public void outADefaultCaseList(ADefaultCaseList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefaultCaseList(ADefaultCaseList node)
    {
        inADefaultCaseList(node);
        if(node.getDefaultStmt() != null)
        {
            node.getDefaultStmt().apply(this);
        }
        outADefaultCaseList(node);
    }

    public void inAEmptyCaseList(AEmptyCaseList node)
    {
        defaultIn(node);
    }

    public void outAEmptyCaseList(AEmptyCaseList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyCaseList(AEmptyCaseList node)
    {
        inAEmptyCaseList(node);
        outAEmptyCaseList(node);
    }

    public void inACaseStmt(ACaseStmt node)
    {
        defaultIn(node);
    }

    public void outACaseStmt(ACaseStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACaseStmt(ACaseStmt node)
    {
        inACaseStmt(node);
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outACaseStmt(node);
    }

    public void inADefaultStmt(ADefaultStmt node)
    {
        defaultIn(node);
    }

    public void outADefaultStmt(ADefaultStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefaultStmt(ADefaultStmt node)
    {
        inADefaultStmt(node);
        if(node.getDefault() != null)
        {
            node.getDefault().apply(this);
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outADefaultStmt(node);
    }

    public void inAWhileLoopStmt(AWhileLoopStmt node)
    {
        defaultIn(node);
    }

    public void outAWhileLoopStmt(AWhileLoopStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileLoopStmt(AWhileLoopStmt node)
    {
        inAWhileLoopStmt(node);
        if(node.getWhileLoop() != null)
        {
            node.getWhileLoop().apply(this);
        }
        outAWhileLoopStmt(node);
    }

    public void inAForLoopStmt(AForLoopStmt node)
    {
        defaultIn(node);
    }

    public void outAForLoopStmt(AForLoopStmt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForLoopStmt(AForLoopStmt node)
    {
        inAForLoopStmt(node);
        if(node.getForLoop() != null)
        {
            node.getForLoop().apply(this);
        }
        outAForLoopStmt(node);
    }

    public void inAWhileLoop(AWhileLoop node)
    {
        defaultIn(node);
    }

    public void outAWhileLoop(AWhileLoop node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileLoop(AWhileLoop node)
    {
        inAWhileLoop(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAWhileLoop(node);
    }

    public void inAForLoop(AForLoop node)
    {
        defaultIn(node);
    }

    public void outAForLoop(AForLoop node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForLoop(AForLoop node)
    {
        inAForLoop(node);
        if(node.getFor() != null)
        {
            node.getFor().apply(this);
        }
        if(node.getLoopExpr() != null)
        {
            node.getLoopExpr().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAForLoop(node);
    }

    public void inAForeachLoopExpr(AForeachLoopExpr node)
    {
        defaultIn(node);
    }

    public void outAForeachLoopExpr(AForeachLoopExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForeachLoopExpr(AForeachLoopExpr node)
    {
        inAForeachLoopExpr(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        outAForeachLoopExpr(node);
    }

    public void inAForLoopExpr(AForLoopExpr node)
    {
        defaultIn(node);
    }

    public void outAForLoopExpr(AForLoopExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForLoopExpr(AForLoopExpr node)
    {
        inAForLoopExpr(node);
        if(node.getInitLoop() != null)
        {
            node.getInitLoop().apply(this);
        }
        if(node.getA() != null)
        {
            node.getA().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getB() != null)
        {
            node.getB().apply(this);
        }
        if(node.getAssignValue() != null)
        {
            node.getAssignValue().apply(this);
        }
        outAForLoopExpr(node);
    }

    public void inADeclareInitLoop(ADeclareInitLoop node)
    {
        defaultIn(node);
    }

    public void outADeclareInitLoop(ADeclareInitLoop node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclareInitLoop(ADeclareInitLoop node)
    {
        inADeclareInitLoop(node);
        if(node.getDcl() != null)
        {
            node.getDcl().apply(this);
        }
        outADeclareInitLoop(node);
    }

    public void inAAssignInitLoop(AAssignInitLoop node)
    {
        defaultIn(node);
    }

    public void outAAssignInitLoop(AAssignInitLoop node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignInitLoop(AAssignInitLoop node)
    {
        inAAssignInitLoop(node);
        if(node.getAssignValue() != null)
        {
            node.getAssignValue().apply(this);
        }
        outAAssignInitLoop(node);
    }

    public void inAAssignValue(AAssignValue node)
    {
        defaultIn(node);
    }

    public void outAAssignValue(AAssignValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignValue(AAssignValue node)
    {
        inAAssignValue(node);
        if(node.getVal() != null)
        {
            node.getVal().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAAssignValue(node);
    }

    public void inATurn(ATurn node)
    {
        defaultIn(node);
    }

    public void outATurn(ATurn node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATurn(ATurn node)
    {
        inATurn(node);
        if(node.getTurn() != null)
        {
            node.getTurn().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outATurn(node);
    }

    public void inAEndCon(AEndCon node)
    {
        defaultIn(node);
    }

    public void outAEndCon(AEndCon node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEndCon(AEndCon node)
    {
        inAEndCon(node);
        if(node.getEndCon() != null)
        {
            node.getEndCon().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outAEndCon(node);
    }

    public void inAEnd(AEnd node)
    {
        defaultIn(node);
    }

    public void outAEnd(AEnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEnd(AEnd node)
    {
        inAEnd(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        outAEnd(node);
    }
}
