/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStmt extends PStmt
{
    private PAssignValue _assignValue_;
    private PEnd _end_;

    public AAssignStmt()
    {
        // Constructor
    }

    public AAssignStmt(
        @SuppressWarnings("hiding") PAssignValue _assignValue_,
        @SuppressWarnings("hiding") PEnd _end_)
    {
        // Constructor
        setAssignValue(_assignValue_);

        setEnd(_end_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStmt(
            cloneNode(this._assignValue_),
            cloneNode(this._end_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStmt(this);
    }

    public PAssignValue getAssignValue()
    {
        return this._assignValue_;
    }

    public void setAssignValue(PAssignValue node)
    {
        if(this._assignValue_ != null)
        {
            this._assignValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignValue_ = node;
    }

    public PEnd getEnd()
    {
        return this._end_;
    }

    public void setEnd(PEnd node)
    {
        if(this._end_ != null)
        {
            this._end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._end_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignValue_)
            + toString(this._end_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignValue_ == child)
        {
            this._assignValue_ = null;
            return;
        }

        if(this._end_ == child)
        {
            this._end_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignValue_ == oldChild)
        {
            setAssignValue((PAssignValue) newChild);
            return;
        }

        if(this._end_ == oldChild)
        {
            setEnd((PEnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
