/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AAssignInitLoop extends PInitLoop
{
    private PAssignValue _assignValue_;

    public AAssignInitLoop()
    {
        // Constructor
    }

    public AAssignInitLoop(
        @SuppressWarnings("hiding") PAssignValue _assignValue_)
    {
        // Constructor
        setAssignValue(_assignValue_);

    }

    @Override
    public Object clone()
    {
        return new AAssignInitLoop(
            cloneNode(this._assignValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignInitLoop(this);
    }

    public PAssignValue getAssignValue()
    {
        return this._assignValue_;
    }

    public void setAssignValue(PAssignValue node)
    {
        if(this._assignValue_ != null)
        {
            this._assignValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignValue_ == child)
        {
            this._assignValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignValue_ == oldChild)
        {
            setAssignValue((PAssignValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
