/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class ACaseCaseStmt extends PCaseStmt
{
    private TCase _case_;

    public ACaseCaseStmt()
    {
        // Constructor
    }

    public ACaseCaseStmt(
        @SuppressWarnings("hiding") TCase _case_)
    {
        // Constructor
        setCase(_case_);

    }

    @Override
    public Object clone()
    {
        return new ACaseCaseStmt(
            cloneNode(this._case_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaseCaseStmt(this);
    }

    public TCase getCase()
    {
        return this._case_;
    }

    public void setCase(TCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._case_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
