/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class ACollectionType extends PType
{
    private PCollection _collection_;

    public ACollectionType()
    {
        // Constructor
    }

    public ACollectionType(
        @SuppressWarnings("hiding") PCollection _collection_)
    {
        // Constructor
        setCollection(_collection_);

    }

    @Override
    public Object clone()
    {
        return new ACollectionType(
            cloneNode(this._collection_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACollectionType(this);
    }

    public PCollection getCollection()
    {
        return this._collection_;
    }

    public void setCollection(PCollection node)
    {
        if(this._collection_ != null)
        {
            this._collection_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._collection_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._collection_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._collection_ == child)
        {
            this._collection_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._collection_ == oldChild)
        {
            setCollection((PCollection) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
