/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import java.util.*;

import P4.CodeGenarator.SemanticException;
import P4.Sable.analysis.*;
import P4.contextualAnalysis.TypeException;

@SuppressWarnings("nls")
public final class ADclStmt extends PStmt
{
    private PType _type_;
    private final LinkedList<PSingleDcl> _dcls_ = new LinkedList<PSingleDcl>();

    public ADclStmt()
    {
        // Constructor
    }

    public ADclStmt(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") List<?> _dcls_)
    {
        // Constructor
        setType(_type_);

        setDcls(_dcls_);

    }

    @Override
    public Object clone()
    {
        return new ADclStmt(
            cloneNode(this._type_),
            cloneList(this._dcls_));
    }

    @Override
    public void apply(Switch sw) throws TypeException, SemanticException {
        ((Analysis) sw).caseADclStmt(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public LinkedList<PSingleDcl> getDcls()
    {
        return this._dcls_;
    }

    public void setDcls(List<?> list)
    {
        for(PSingleDcl e : this._dcls_)
        {
            e.parent(null);
        }
        this._dcls_.clear();

        for(Object obj_e : list)
        {
            PSingleDcl e = (PSingleDcl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._dcls_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._dcls_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._dcls_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        for(ListIterator<PSingleDcl> i = this._dcls_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSingleDcl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
