/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class ADclList extends PDclList
{
    private TSeparator _separator_;
    private PSingleDcl _singleDcl_;

    public ADclList()
    {
        // Constructor
    }

    public ADclList(
        @SuppressWarnings("hiding") TSeparator _separator_,
        @SuppressWarnings("hiding") PSingleDcl _singleDcl_)
    {
        // Constructor
        setSeparator(_separator_);

        setSingleDcl(_singleDcl_);

    }

    @Override
    public Object clone()
    {
        return new ADclList(
            cloneNode(this._separator_),
            cloneNode(this._singleDcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADclList(this);
    }

    public TSeparator getSeparator()
    {
        return this._separator_;
    }

    public void setSeparator(TSeparator node)
    {
        if(this._separator_ != null)
        {
            this._separator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separator_ = node;
    }

    public PSingleDcl getSingleDcl()
    {
        return this._singleDcl_;
    }

    public void setSingleDcl(PSingleDcl node)
    {
        if(this._singleDcl_ != null)
        {
            this._singleDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleDcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separator_)
            + toString(this._singleDcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separator_ == child)
        {
            this._separator_ = null;
            return;
        }

        if(this._singleDcl_ == child)
        {
            this._singleDcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separator_ == oldChild)
        {
            setSeparator((TSeparator) newChild);
            return;
        }

        if(this._singleDcl_ == oldChild)
        {
            setSingleDcl((PSingleDcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
