/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import java.util.*;
import P4.Sable.analysis.*;
import P4.symbolTable.TypeException;

@SuppressWarnings("nls")
public final class AElement extends PElement
{
    private final LinkedList<PExpr> _values_ = new LinkedList<PExpr>();

    public AElement()
    {
        // Constructor
    }

    public AElement(
        @SuppressWarnings("hiding") List<?> _values_)
    {
        // Constructor
        setValues(_values_);

    }

    @Override
    public Object clone()
    {
        return new AElement(
            cloneList(this._values_));
    }

    @Override
    public void apply(Switch sw) throws TypeException
    {
        ((Analysis) sw).caseAElement(this);
    }

    public LinkedList<PExpr> getValues()
    {
        return this._values_;
    }

    public void setValues(List<?> list)
    {
        for(PExpr e : this._values_)
        {
            e.parent(null);
        }
        this._values_.clear();

        for(Object obj_e : list)
        {
            PExpr e = (PExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._values_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._values_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._values_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpr> i = this._values_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
