/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AExpandFactor extends PFactor
{
    private PParens _parens_;

    public AExpandFactor()
    {
        // Constructor
    }

    public AExpandFactor(
        @SuppressWarnings("hiding") PParens _parens_)
    {
        // Constructor
        setParens(_parens_);

    }

    @Override
    public Object clone()
    {
        return new AExpandFactor(
            cloneNode(this._parens_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandFactor(this);
    }

    public PParens getParens()
    {
        return this._parens_;
    }

    public void setParens(PParens node)
    {
        if(this._parens_ != null)
        {
            this._parens_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parens_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parens_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parens_ == child)
        {
            this._parens_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parens_ == oldChild)
        {
            setParens((PParens) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
