/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AExpandAddExpr extends PAddExpr
{
    private PAddExpr _addExpr_;
    private TAddOp _addOp_;
    private PTerm _term_;

    public AExpandAddExpr()
    {
        // Constructor
    }

    public AExpandAddExpr(
        @SuppressWarnings("hiding") PAddExpr _addExpr_,
        @SuppressWarnings("hiding") TAddOp _addOp_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setAddExpr(_addExpr_);

        setAddOp(_addOp_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new AExpandAddExpr(
            cloneNode(this._addExpr_),
            cloneNode(this._addOp_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandAddExpr(this);
    }

    public PAddExpr getAddExpr()
    {
        return this._addExpr_;
    }

    public void setAddExpr(PAddExpr node)
    {
        if(this._addExpr_ != null)
        {
            this._addExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExpr_ = node;
    }

    public TAddOp getAddOp()
    {
        return this._addOp_;
    }

    public void setAddOp(TAddOp node)
    {
        if(this._addOp_ != null)
        {
            this._addOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addOp_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addExpr_)
            + toString(this._addOp_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addExpr_ == child)
        {
            this._addExpr_ = null;
            return;
        }

        if(this._addOp_ == child)
        {
            this._addOp_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addExpr_ == oldChild)
        {
            setAddExpr((PAddExpr) newChild);
            return;
        }

        if(this._addOp_ == oldChild)
        {
            setAddOp((TAddOp) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
