/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AExpandExpr extends PExpr
{
    private PExpr _expr_;
    private TBoolOp _boolOp_;
    private PEquality _equality_;

    public AExpandExpr()
    {
        // Constructor
    }

    public AExpandExpr(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TBoolOp _boolOp_,
        @SuppressWarnings("hiding") PEquality _equality_)
    {
        // Constructor
        setExpr(_expr_);

        setBoolOp(_boolOp_);

        setEquality(_equality_);

    }

    @Override
    public Object clone()
    {
        return new AExpandExpr(
            cloneNode(this._expr_),
            cloneNode(this._boolOp_),
            cloneNode(this._equality_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandExpr(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TBoolOp getBoolOp()
    {
        return this._boolOp_;
    }

    public void setBoolOp(TBoolOp node)
    {
        if(this._boolOp_ != null)
        {
            this._boolOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolOp_ = node;
    }

    public PEquality getEquality()
    {
        return this._equality_;
    }

    public void setEquality(PEquality node)
    {
        if(this._equality_ != null)
        {
            this._equality_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equality_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._boolOp_)
            + toString(this._equality_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._boolOp_ == child)
        {
            this._boolOp_ = null;
            return;
        }

        if(this._equality_ == child)
        {
            this._equality_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._boolOp_ == oldChild)
        {
            setBoolOp((TBoolOp) newChild);
            return;
        }

        if(this._equality_ == oldChild)
        {
            setEquality((PEquality) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
