/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AExpandParamDclList extends PParamDclList
{
    private PParamDcl _paramDcl_;
    private TSeparator _separator_;
    private PParamDclList _paramDclList_;

    public AExpandParamDclList()
    {
        // Constructor
    }

    public AExpandParamDclList(
        @SuppressWarnings("hiding") PParamDcl _paramDcl_,
        @SuppressWarnings("hiding") TSeparator _separator_,
        @SuppressWarnings("hiding") PParamDclList _paramDclList_)
    {
        // Constructor
        setParamDcl(_paramDcl_);

        setSeparator(_separator_);

        setParamDclList(_paramDclList_);

    }

    @Override
    public Object clone()
    {
        return new AExpandParamDclList(
            cloneNode(this._paramDcl_),
            cloneNode(this._separator_),
            cloneNode(this._paramDclList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandParamDclList(this);
    }

    public PParamDcl getParamDcl()
    {
        return this._paramDcl_;
    }

    public void setParamDcl(PParamDcl node)
    {
        if(this._paramDcl_ != null)
        {
            this._paramDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramDcl_ = node;
    }

    public TSeparator getSeparator()
    {
        return this._separator_;
    }

    public void setSeparator(TSeparator node)
    {
        if(this._separator_ != null)
        {
            this._separator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separator_ = node;
    }

    public PParamDclList getParamDclList()
    {
        return this._paramDclList_;
    }

    public void setParamDclList(PParamDclList node)
    {
        if(this._paramDclList_ != null)
        {
            this._paramDclList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramDclList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paramDcl_)
            + toString(this._separator_)
            + toString(this._paramDclList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paramDcl_ == child)
        {
            this._paramDcl_ = null;
            return;
        }

        if(this._separator_ == child)
        {
            this._separator_ = null;
            return;
        }

        if(this._paramDclList_ == child)
        {
            this._paramDclList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paramDcl_ == oldChild)
        {
            setParamDcl((PParamDcl) newChild);
            return;
        }

        if(this._separator_ == oldChild)
        {
            setSeparator((TSeparator) newChild);
            return;
        }

        if(this._paramDclList_ == oldChild)
        {
            setParamDclList((PParamDclList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
