/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AExpandEquality extends PEquality
{
    private PEquality _equality_;
    private TEqualOp _equalOp_;
    private PRelation _relation_;

    public AExpandEquality()
    {
        // Constructor
    }

    public AExpandEquality(
        @SuppressWarnings("hiding") PEquality _equality_,
        @SuppressWarnings("hiding") TEqualOp _equalOp_,
        @SuppressWarnings("hiding") PRelation _relation_)
    {
        // Constructor
        setEquality(_equality_);

        setEqualOp(_equalOp_);

        setRelation(_relation_);

    }

    @Override
    public Object clone()
    {
        return new AExpandEquality(
            cloneNode(this._equality_),
            cloneNode(this._equalOp_),
            cloneNode(this._relation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpandEquality(this);
    }

    public PEquality getEquality()
    {
        return this._equality_;
    }

    public void setEquality(PEquality node)
    {
        if(this._equality_ != null)
        {
            this._equality_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equality_ = node;
    }

    public TEqualOp getEqualOp()
    {
        return this._equalOp_;
    }

    public void setEqualOp(TEqualOp node)
    {
        if(this._equalOp_ != null)
        {
            this._equalOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalOp_ = node;
    }

    public PRelation getRelation()
    {
        return this._relation_;
    }

    public void setRelation(PRelation node)
    {
        if(this._relation_ != null)
        {
            this._relation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equality_)
            + toString(this._equalOp_)
            + toString(this._relation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equality_ == child)
        {
            this._equality_ = null;
            return;
        }

        if(this._equalOp_ == child)
        {
            this._equalOp_ = null;
            return;
        }

        if(this._relation_ == child)
        {
            this._relation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equality_ == oldChild)
        {
            setEquality((PEquality) newChild);
            return;
        }

        if(this._equalOp_ == oldChild)
        {
            setEqualOp((TEqualOp) newChild);
            return;
        }

        if(this._relation_ == oldChild)
        {
            setRelation((PRelation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
