/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AForLoopStmt extends PLoopStmt
{
    private PForLoop _forLoop_;

    public AForLoopStmt()
    {
        // Constructor
    }

    public AForLoopStmt(
        @SuppressWarnings("hiding") PForLoop _forLoop_)
    {
        // Constructor
        setForLoop(_forLoop_);

    }

    @Override
    public Object clone()
    {
        return new AForLoopStmt(
            cloneNode(this._forLoop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForLoopStmt(this);
    }

    public PForLoop getForLoop()
    {
        return this._forLoop_;
    }

    public void setForLoop(PForLoop node)
    {
        if(this._forLoop_ != null)
        {
            this._forLoop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forLoop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forLoop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forLoop_ == child)
        {
            this._forLoop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forLoop_ == oldChild)
        {
            setForLoop((PForLoop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
