/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import java.util.*;
import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AForeachStmt extends PStmt
{
    private TId _id_;
    private PVal _list_;
    private final LinkedList<PStmt> _then_ = new LinkedList<PStmt>();

    public AForeachStmt()
    {
        // Constructor
    }

    public AForeachStmt(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PVal _list_,
        @SuppressWarnings("hiding") List<?> _then_)
    {
        // Constructor
        setId(_id_);

        setList(_list_);

        setThen(_then_);

    }

    @Override
    public Object clone()
    {
        return new AForeachStmt(
            cloneNode(this._id_),
            cloneNode(this._list_),
            cloneList(this._then_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForeachStmt(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PVal getList()
    {
        return this._list_;
    }

    public void setList(PVal node)
    {
        if(this._list_ != null)
        {
            this._list_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._list_ = node;
    }

    public LinkedList<PStmt> getThen()
    {
        return this._then_;
    }

    public void setThen(List<?> list)
    {
        for(PStmt e : this._then_)
        {
            e.parent(null);
        }
        this._then_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._then_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._list_)
            + toString(this._then_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._list_ == child)
        {
            this._list_ = null;
            return;
        }

        if(this._then_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._list_ == oldChild)
        {
            setList((PVal) newChild);
            return;
        }

        for(ListIterator<PStmt> i = this._then_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
