/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AInitFactor extends PFactor
{
    private PInitList _initList_;

    public AInitFactor()
    {
        // Constructor
    }

    public AInitFactor(
        @SuppressWarnings("hiding") PInitList _initList_)
    {
        // Constructor
        setInitList(_initList_);

    }

    @Override
    public Object clone()
    {
        return new AInitFactor(
            cloneNode(this._initList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitFactor(this);
    }

    public PInitList getInitList()
    {
        return this._initList_;
    }

    public void setInitList(PInitList node)
    {
        if(this._initList_ != null)
        {
            this._initList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._initList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._initList_ == child)
        {
            this._initList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._initList_ == oldChild)
        {
            setInitList((PInitList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
