/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class ASelectStmt extends PStmt
{
    private PSelectStmt _selectStmt_;

    public ASelectStmt()
    {
        // Constructor
    }

    public ASelectStmt(
        @SuppressWarnings("hiding") PSelectStmt _selectStmt_)
    {
        // Constructor
        setSelectStmt(_selectStmt_);

    }

    @Override
    public Object clone()
    {
        return new ASelectStmt(
            cloneNode(this._selectStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectStmt(this);
    }

    public PSelectStmt getSelectStmt()
    {
        return this._selectStmt_;
    }

    public void setSelectStmt(PSelectStmt node)
    {
        if(this._selectStmt_ != null)
        {
            this._selectStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._selectStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._selectStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._selectStmt_ == child)
        {
            this._selectStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._selectStmt_ == oldChild)
        {
            setSelectStmt((PSelectStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
