/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class ASwitchSelectStmt extends PSelectStmt
{
    private PSwitchStmt _switchStmt_;

    public ASwitchSelectStmt()
    {
        // Constructor
    }

    public ASwitchSelectStmt(
        @SuppressWarnings("hiding") PSwitchStmt _switchStmt_)
    {
        // Constructor
        setSwitchStmt(_switchStmt_);

    }

    @Override
    public Object clone()
    {
        return new ASwitchSelectStmt(
            cloneNode(this._switchStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASwitchSelectStmt(this);
    }

    public PSwitchStmt getSwitchStmt()
    {
        return this._switchStmt_;
    }

    public void setSwitchStmt(PSwitchStmt node)
    {
        if(this._switchStmt_ != null)
        {
            this._switchStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._switchStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._switchStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._switchStmt_ == child)
        {
            this._switchStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._switchStmt_ == oldChild)
        {
            setSwitchStmt((PSwitchStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
