/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import java.util.*;

import P4.CodeGenarator.SemanticException;
import P4.Sable.analysis.*;
import P4.contextualAnalysis.TypeException;

@SuppressWarnings("nls")
public final class ASwitchStmt extends PStmt
{
    private PVal _variable_;
    private final LinkedList<PCase> _cases_ = new LinkedList<PCase>();

    public ASwitchStmt()
    {
        // Constructor
    }

    public ASwitchStmt(
        @SuppressWarnings("hiding") PVal _variable_,
        @SuppressWarnings("hiding") List<?> _cases_)
    {
        // Constructor
        setVariable(_variable_);

        setCases(_cases_);

    }

    @Override
    public Object clone()
    {
        return new ASwitchStmt(
            cloneNode(this._variable_),
            cloneList(this._cases_));
    }

    @Override
    public void apply(Switch sw) throws TypeException, SemanticException {
        ((Analysis) sw).caseASwitchStmt(this);
    }

    public PVal getVariable()
    {
        return this._variable_;
    }

    public void setVariable(PVal node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    public LinkedList<PCase> getCases()
    {
        return this._cases_;
    }

    public void setCases(List<?> list)
    {
        for(PCase e : this._cases_)
        {
            e.parent(null);
        }
        this._cases_.clear();

        for(Object obj_e : list)
        {
            PCase e = (PCase) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._cases_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variable_)
            + toString(this._cases_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        if(this._cases_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variable_ == oldChild)
        {
            setVariable((PVal) newChild);
            return;
        }

        for(ListIterator<PCase> i = this._cases_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCase) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
