/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import java.util.*;

import P4.CodeGenarator.SemanticException;
import P4.Sable.analysis.*;
import P4.contextualAnalysis.TypeException;

@SuppressWarnings("nls")
public final class AVal extends PVal
{
    private final LinkedList<PCallField> _callField_ = new LinkedList<PCallField>();

    public AVal()
    {
        // Constructor
    }

    public AVal(
        @SuppressWarnings("hiding") List<?> _callField_)
    {
        // Constructor
        setCallField(_callField_);

    }

    @Override
    public Object clone()
    {
        return new AVal(
            cloneList(this._callField_));
    }

    @Override
    public void apply(Switch sw) throws TypeException, SemanticException {
        ((Analysis) sw).caseAVal(this);
    }

    public LinkedList<PCallField> getCallField()
    {
        return this._callField_;
    }

    public void setCallField(List<?> list)
    {
        for(PCallField e : this._callField_)
        {
            e.parent(null);
        }
        this._callField_.clear();

        for(Object obj_e : list)
        {
            PCallField e = (PCallField) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._callField_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._callField_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._callField_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PCallField> i = this._callField_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCallField) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
