/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.Sable.analysis.*;

@SuppressWarnings("nls")
public final class AWhileLoopStmt extends PLoopStmt
{
    private PWhileLoop _whileLoop_;

    public AWhileLoopStmt()
    {
        // Constructor
    }

    public AWhileLoopStmt(
        @SuppressWarnings("hiding") PWhileLoop _whileLoop_)
    {
        // Constructor
        setWhileLoop(_whileLoop_);

    }

    @Override
    public Object clone()
    {
        return new AWhileLoopStmt(
            cloneNode(this._whileLoop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileLoopStmt(this);
    }

    public PWhileLoop getWhileLoop()
    {
        return this._whileLoop_;
    }

    public void setWhileLoop(PWhileLoop node)
    {
        if(this._whileLoop_ != null)
        {
            this._whileLoop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileLoop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileLoop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileLoop_ == child)
        {
            this._whileLoop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileLoop_ == oldChild)
        {
            setWhileLoop((PWhileLoop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
