/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.node;

import P4.CodeGenarator.SemanticException;
import P4.contextualAnalysis.TypeException;

public interface Switchable
{
    void apply(Switch sw) throws TypeException, SemanticException;

}
