/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.lexer;

import java.io.*;
import P4.Sable.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolLiteral(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAddOp(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultOp(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntLiteral(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatLiteral(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolOp(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelationOp(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqualOp(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLParen(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRParen(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrack(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrack(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetup(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrivate(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeparator(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMoves(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBox(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBox(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSwitch(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefault(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TForeach(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTurn(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndCon(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCard(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLArr(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRArr(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TList(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTypeof(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFun(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInc(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {37, 37, 7}, {38, 38, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 48, 17}, {49, 57, 18}, {58, 58, 19}, {59, 59, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 66, 24}, {67, 67, 25}, {68, 68, 24}, {69, 69, 26}, {70, 70, 27}, {71, 75, 24}, {76, 76, 28}, {77, 77, 29}, {78, 79, 24}, {80, 80, 30}, {81, 82, 24}, {83, 83, 31}, {84, 84, 32}, {85, 90, 24}, {91, 91, 33}, {93, 93, 34}, {97, 98, 35}, {99, 99, 36}, {100, 100, 37}, {101, 101, 38}, {102, 102, 39}, {103, 104, 35}, {105, 105, 40}, {106, 113, 35}, {114, 114, 41}, {115, 115, 42}, {116, 116, 43}, {117, 118, 35}, {119, 119, 44}, {120, 122, 35}, {123, 123, 45}, {124, 124, 46}, {125, 125, 47}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 48}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 49}, },
            {{0, 9, 50}, {11, 12, 50}, {14, 33, 50}, {34, 34, 51}, {35, 65535, 50}, },
            {{61, 61, 52}, },
            {{61, 61, 53}, },
            {},
            {},
            {{61, 61, 54}, },
            {{61, 61, 55}, },
            {},
            {{61, 61, 56}, },
            {},
            {{47, 47, 57}, {61, 61, 58}, },
            {{48, 57, 17}, },
            {{46, 46, 59}, {48, 57, 60}, },
            {},
            {},
            {{61, 61, 61}, },
            {{61, 61, 62}, },
            {{61, 61, 63}, },
            {{48, 57, 64}, {65, 90, 65}, {97, 122, 66}, },
            {{48, 90, -26}, {97, 97, 67}, {98, 122, 66}, },
            {{48, 90, -26}, {97, 109, 66}, {110, 110, 68}, {111, 122, 66}, },
            {{48, 90, -26}, {97, 116, 66}, {117, 117, 69}, {118, 122, 66}, },
            {{48, 90, -26}, {97, 104, 66}, {105, 105, 70}, {106, 122, 66}, },
            {{48, 90, -26}, {97, 110, 66}, {111, 111, 71}, {112, 122, 66}, },
            {{48, 90, -26}, {97, 113, 66}, {114, 114, 72}, {115, 116, 66}, {117, 117, 73}, {118, 122, 66}, },
            {{48, 90, -26}, {97, 100, 66}, {101, 101, 74}, {102, 116, 66}, {117, 117, 75}, {118, 122, 66}, },
            {{48, 116, -29}, {117, 117, 76}, {118, 122, 66}, },
            {},
            {},
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 97, 77}, {98, 122, 66}, },
            {{48, 100, -33}, {101, 101, 78}, {102, 122, 66}, },
            {{48, 90, -26}, {97, 107, 66}, {108, 108, 79}, {109, 122, 66}, },
            {{48, 90, -26}, {97, 97, 80}, {98, 110, 66}, {111, 111, 81}, {112, 122, 66}, },
            {{48, 90, -26}, {97, 101, 66}, {102, 102, 82}, {103, 109, 66}, {110, 110, 83}, {111, 122, 66}, },
            {{48, 100, -33}, {101, 101, 84}, {102, 122, 66}, },
            {{48, 90, -26}, {97, 118, 66}, {119, 119, 85}, {120, 122, 66}, },
            {{48, 113, -32}, {114, 114, 86}, {115, 120, 66}, {121, 121, 87}, {122, 122, 66}, },
            {{48, 90, -26}, {97, 103, 66}, {104, 104, 88}, {105, 122, 66}, },
            {},
            {{61, 61, 89}, },
            {},
            {{9, 32, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{0, 9, 90}, {10, 10, 91}, {11, 12, 90}, {13, 13, 92}, {14, 65535, 90}, },
            {},
            {{48, 57, 93}, },
            {{46, 57, -20}, },
            {},
            {},
            {},
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 113, -32}, {114, 114, 94}, {115, 122, 66}, },
            {{48, 90, -26}, {97, 99, 66}, {100, 100, 95}, {101, 122, 66}, },
            {{48, 109, -28}, {110, 110, 96}, {111, 122, 66}, },
            {{48, 90, -26}, {97, 114, 66}, {115, 115, 97}, {116, 122, 66}, },
            {{48, 90, -26}, {97, 117, 66}, {118, 118, 98}, {119, 122, 66}, },
            {{48, 104, -30}, {105, 105, 99}, {106, 122, 66}, },
            {{48, 90, -26}, {97, 97, 66}, {98, 98, 100}, {99, 122, 66}, },
            {{48, 90, -26}, {97, 115, 66}, {116, 116, 101}, {117, 122, 66}, },
            {{48, 97, -75}, {98, 98, 102}, {99, 122, 66}, },
            {{48, 113, -32}, {114, 114, 103}, {115, 122, 66}, },
            {{48, 114, -72}, {115, 115, 104}, {116, 122, 66}, },
            {{48, 101, -42}, {102, 102, 105}, {103, 122, 66}, },
            {{48, 114, -72}, {115, 115, 106}, {116, 122, 66}, },
            {{48, 107, -40}, {108, 108, 107}, {109, 122, 66}, },
            {{48, 113, -32}, {114, 114, 108}, {115, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 98, 66}, {99, 99, 109}, {100, 122, 66}, },
            {{48, 115, -76}, {116, 116, 110}, {117, 122, 66}, },
            {{48, 104, -30}, {105, 105, 111}, {106, 122, 66}, },
            {{48, 116, -29}, {117, 117, 112}, {118, 122, 66}, },
            {{48, 90, -26}, {97, 111, 66}, {112, 112, 113}, {113, 122, 66}, },
            {{48, 104, -30}, {105, 105, 114}, {106, 122, 66}, },
            {},
            {{0, 65535, -59}, },
            {},
            {{10, 10, 115}, },
            {{48, 57, 93}, },
            {{48, 99, -70}, {100, 100, 116}, {101, 122, 66}, },
            {{48, 57, 64}, {65, 66, 65}, {67, 67, 117}, {68, 90, 65}, {97, 122, 66}, },
            {{48, 98, -85}, {99, 99, 118}, {100, 122, 66}, },
            {{48, 115, -76}, {116, 116, 119}, {117, 122, 66}, },
            {{48, 100, -33}, {101, 101, 120}, {102, 122, 66}, },
            {{48, 117, -73}, {118, 118, 121}, {119, 122, 66}, },
            {{48, 107, -40}, {108, 108, 122}, {109, 122, 66}, },
            {{48, 116, -29}, {117, 117, 123}, {118, 122, 66}, },
            {{48, 98, -85}, {99, 99, 124}, {100, 122, 66}, },
            {{48, 109, -28}, {110, 110, 125}, {111, 122, 66}, },
            {{48, 100, -33}, {101, 101, 126}, {102, 122, 66}, },
            {{48, 90, -26}, {97, 97, 127}, {98, 122, 66}, },
            {{48, 100, -33}, {101, 101, 128}, {102, 122, 66}, },
            {{48, 114, -72}, {115, 115, 129}, {116, 122, 66}, },
            {{48, 100, -33}, {101, 101, 130}, {102, 122, 66}, },
            {{48, 107, -40}, {108, 108, 131}, {109, 122, 66}, },
            {{48, 116, -29}, {117, 117, 132}, {118, 122, 66}, },
            {{48, 115, -76}, {116, 116, 133}, {117, 122, 66}, },
            {{48, 100, -33}, {101, 101, 134}, {102, 122, 66}, },
            {{48, 100, -33}, {101, 101, 135}, {102, 122, 66}, },
            {{48, 107, -40}, {108, 108, 136}, {109, 122, 66}, },
            {},
            {{48, 122, -26}, },
            {{48, 110, -31}, {111, 111, 137}, {112, 122, 66}, },
            {{48, 115, -76}, {116, 116, 138}, {117, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 114, -72}, {115, 115, 139}, {116, 122, 66}, },
            {{48, 90, -26}, {97, 97, 140}, {98, 122, 66}, },
            {{48, 104, -30}, {105, 105, 141}, {106, 122, 66}, },
            {{48, 111, -89}, {112, 112, 142}, {113, 122, 66}, },
            {{48, 107, -40}, {108, 108, 143}, {109, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 116, -29}, {117, 117, 144}, {118, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 100, -33}, {101, 101, 145}, {102, 122, 66}, },
            {{48, 90, -26}, {97, 97, 146}, {98, 122, 66}, },
            {{48, 116, -29}, {117, 117, 147}, {118, 122, 66}, },
            {{48, 113, -32}, {114, 114, 148}, {115, 122, 66}, },
            {{48, 98, -85}, {99, 99, 149}, {100, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 110, -31}, {111, 111, 150}, {112, 122, 66}, },
            {{48, 100, -33}, {101, 101, 151}, {102, 122, 66}, },
            {{48, 109, -28}, {110, 110, 152}, {111, 122, 66}, },
            {{48, 104, -30}, {105, 105, 153}, {106, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 115, -76}, {116, 116, 154}, {117, 122, 66}, },
            {{48, 98, -85}, {99, 99, 155}, {100, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 90, -26}, {97, 97, 156}, {98, 122, 66}, },
            {{48, 107, -40}, {108, 108, 157}, {109, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 98, -85}, {99, 99, 158}, {100, 122, 66}, },
            {{48, 99, -70}, {100, 100, 159}, {101, 122, 66}, },
            {{48, 109, -28}, {110, 110, 160}, {111, 122, 66}, },
            {{48, 103, -46}, {104, 104, 161}, {105, 122, 66}, },
            {{48, 101, -42}, {102, 102, 162}, {103, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 99, -70}, {100, 100, 163}, {101, 122, 66}, },
            {{48, 110, -31}, {111, 111, 164}, {112, 122, 66}, },
            {{48, 100, -33}, {101, 101, 165}, {102, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 114, -72}, {115, 115, 166}, {116, 122, 66}, },
            {{48, 115, -76}, {116, 116, 167}, {117, 122, 66}, },
            {{48, 103, -46}, {104, 104, 168}, {105, 122, 66}, },
            {{48, 100, -33}, {101, 101, 169}, {102, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 104, -30}, {105, 105, 170}, {106, 122, 66}, },
            {{48, 109, -28}, {110, 110, 171}, {111, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 114, -72}, {115, 115, 172}, {116, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 115, -76}, {116, 116, 173}, {117, 122, 66}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 104, -30}, {105, 105, 174}, {106, 122, 66}, },
            {{48, 110, -31}, {111, 111, 175}, {112, 122, 66}, },
            {{48, 109, -28}, {110, 110, 176}, {111, 122, 66}, },
            {{48, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {5, 0, 0, 0, 0, -1, -1, 4, 8, 12, 13, 4, 3, 19, 3, 20, 4, 5, 5, 31, 25, 9, 10, 9, 46, 46, 46, 46, 46, 46, 46, 46, 46, 22, 23, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 14, 8, 15, 0, 11, -1, 7, 10, 10, 10, 10, 10, -1, 10, 6, 5, 9, 11, 9, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 26, 37, 46, 46, 46, 46, 46, 10, -1, 1, 1, 6, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 33, 46, 46, 46, 46, 46, 46, 1, 38, 46, 46, 41, 46, 46, 46, 46, 46, 35, 29, 46, 27, 46, 46, 46, 46, 46, 2, 46, 46, 46, 46, 21, 46, 46, 16, 46, 46, 2, 46, 46, 46, 46, 46, 32, 46, 46, 46, 17, 46, 46, 46, 46, 24, 28, 42, 46, 46, 18, 46, 30, 34, 44, 46, 43, 45, 46, 46, 46, 36, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
