/* This file was generated by SableCC (http://www.sablecc.org/). */

package P4.Sable.lexer;

import java.io.*;
import P4.Sable.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolLiteral(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAddOp(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultOp(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntLiteral(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatLiteral(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolOp(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelationOp(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqualOp(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLParen(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRParen(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrack(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrack(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetup(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrivate(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeparator(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMoves(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBox(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBox(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSwitch(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefault(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TForeach(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTurn(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndCon(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TType(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLArr(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRArr(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TList(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTypeof(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFun(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {37, 37, 6}, {38, 38, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 48, 17}, {49, 57, 18}, {58, 58, 19}, {59, 59, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 66, 24}, {67, 67, 25}, {68, 68, 24}, {69, 69, 26}, {70, 70, 27}, {71, 75, 24}, {76, 76, 28}, {77, 77, 29}, {78, 79, 24}, {80, 80, 30}, {81, 82, 24}, {83, 83, 31}, {84, 84, 32}, {85, 90, 24}, {91, 91, 33}, {93, 93, 34}, {97, 97, 35}, {98, 98, 36}, {99, 99, 37}, {100, 100, 38}, {101, 101, 39}, {102, 102, 40}, {103, 104, 35}, {105, 105, 41}, {106, 113, 35}, {114, 114, 42}, {115, 115, 43}, {116, 116, 44}, {117, 117, 35}, {118, 118, 45}, {119, 119, 46}, {120, 122, 35}, {123, 123, 47}, {124, 124, 48}, {125, 125, 49}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 50}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 51}, },
            {{61, 61, 52}, },
            {{38, 38, 53}, {61, 61, 54}, },
            {{0, 9, 55}, {11, 12, 55}, {14, 38, 55}, {39, 39, 56}, {40, 65535, 55}, },
            {},
            {},
            {{61, 61, 57}, },
            {{61, 61, 58}, },
            {},
            {{61, 61, 59}, },
            {},
            {{47, 47, 60}, {61, 61, 61}, },
            {{48, 57, 17}, },
            {{46, 46, 62}, {48, 57, 63}, },
            {},
            {},
            {{61, 61, 64}, },
            {{61, 61, 65}, },
            {{61, 61, 66}, },
            {{48, 57, 67}, {65, 90, 68}, {97, 122, 69}, },
            {{48, 90, -26}, {97, 97, 70}, {98, 122, 69}, },
            {{48, 90, -26}, {97, 109, 69}, {110, 110, 71}, {111, 122, 69}, },
            {{48, 90, -26}, {97, 116, 69}, {117, 117, 72}, {118, 122, 69}, },
            {{48, 90, -26}, {97, 104, 69}, {105, 105, 73}, {106, 122, 69}, },
            {{48, 90, -26}, {97, 110, 69}, {111, 111, 74}, {112, 122, 69}, },
            {{48, 90, -26}, {97, 107, 69}, {108, 108, 75}, {109, 113, 69}, {114, 114, 76}, {115, 116, 69}, {117, 117, 77}, {118, 122, 69}, },
            {{48, 90, -26}, {97, 100, 69}, {101, 101, 78}, {102, 122, 69}, },
            {{48, 116, -29}, {117, 117, 79}, {118, 122, 69}, },
            {},
            {},
            {{48, 122, -26}, },
            {{48, 110, -31}, {111, 111, 80}, {112, 122, 69}, },
            {{48, 90, -26}, {97, 97, 81}, {98, 122, 69}, },
            {{48, 100, -33}, {101, 101, 82}, {102, 122, 69}, },
            {{48, 107, -32}, {108, 108, 83}, {109, 122, 69}, },
            {{48, 90, -26}, {97, 97, 84}, {98, 107, 69}, {108, 108, 85}, {109, 110, 69}, {111, 111, 86}, {112, 122, 69}, },
            {{48, 90, -26}, {97, 101, 69}, {102, 102, 87}, {103, 109, 69}, {110, 110, 88}, {111, 122, 69}, },
            {{48, 100, -33}, {101, 101, 89}, {102, 122, 69}, },
            {{48, 90, -26}, {97, 115, 69}, {116, 116, 90}, {117, 118, 69}, {119, 119, 91}, {120, 122, 69}, },
            {{48, 90, -26}, {97, 113, 69}, {114, 114, 92}, {115, 120, 69}, {121, 121, 93}, {122, 122, 69}, },
            {{48, 110, -31}, {111, 111, 94}, {112, 122, 69}, },
            {{48, 90, -26}, {97, 103, 69}, {104, 104, 95}, {105, 122, 69}, },
            {},
            {{61, 61, 96}, {124, 124, 97}, },
            {},
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {{0, 65535, -10}, },
            {},
            {},
            {},
            {},
            {{0, 9, 98}, {10, 10, 99}, {11, 12, 98}, {13, 13, 100}, {14, 65535, 98}, },
            {},
            {{48, 57, 101}, },
            {{46, 57, -20}, },
            {},
            {},
            {},
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 113, -46}, {114, 114, 102}, {115, 122, 69}, },
            {{48, 90, -26}, {97, 99, 69}, {100, 100, 103}, {101, 122, 69}, },
            {{48, 109, -28}, {110, 110, 104}, {111, 122, 69}, },
            {{48, 90, -26}, {97, 114, 69}, {115, 115, 105}, {116, 122, 69}, },
            {{48, 90, -26}, {97, 117, 69}, {118, 118, 106}, {119, 122, 69}, },
            {{48, 90, -26}, {97, 97, 107}, {98, 122, 69}, },
            {{48, 104, -30}, {105, 105, 108}, {106, 122, 69}, },
            {{48, 90, -26}, {97, 97, 69}, {98, 98, 109}, {99, 122, 69}, },
            {{48, 115, -45}, {116, 116, 110}, {117, 122, 69}, },
            {{48, 113, -46}, {114, 114, 111}, {115, 122, 69}, },
            {{48, 110, -31}, {111, 111, 112}, {112, 122, 69}, },
            {{48, 114, -75}, {115, 115, 113}, {116, 122, 69}, },
            {{48, 101, -43}, {102, 102, 114}, {103, 122, 69}, },
            {{48, 114, -75}, {115, 115, 115}, {116, 122, 69}, },
            {{48, 107, -32}, {108, 108, 116}, {109, 122, 69}, },
            {{48, 110, -31}, {111, 111, 117}, {112, 122, 69}, },
            {{48, 113, -46}, {114, 114, 118}, {115, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 115, -45}, {116, 116, 119}, {117, 122, 69}, },
            {{48, 115, -45}, {116, 116, 120}, {117, 122, 69}, },
            {{48, 113, -46}, {114, 114, 121}, {115, 122, 69}, },
            {{48, 104, -30}, {105, 105, 122}, {106, 122, 69}, },
            {{48, 116, -29}, {117, 117, 123}, {118, 122, 69}, },
            {{48, 90, -26}, {97, 111, 69}, {112, 112, 124}, {113, 122, 69}, },
            {{48, 104, -30}, {105, 105, 125}, {106, 122, 69}, },
            {{48, 104, -30}, {105, 105, 126}, {106, 122, 69}, },
            {},
            {},
            {{0, 65535, -62}, },
            {},
            {{10, 10, 127}, },
            {{48, 57, 101}, },
            {{48, 99, -73}, {100, 100, 128}, {101, 122, 69}, },
            {{48, 57, 67}, {65, 66, 68}, {67, 67, 129}, {68, 90, 68}, {97, 122, 69}, },
            {{48, 90, -26}, {97, 98, 69}, {99, 99, 130}, {100, 122, 69}, },
            {{48, 115, -45}, {116, 116, 131}, {117, 122, 69}, },
            {{48, 100, -33}, {101, 101, 132}, {102, 122, 69}, },
            {{48, 90, -26}, {97, 120, 69}, {121, 121, 133}, {122, 122, 69}, },
            {{48, 117, -76}, {118, 118, 134}, {119, 122, 69}, },
            {{48, 107, -32}, {108, 108, 135}, {109, 122, 69}, },
            {{48, 116, -29}, {117, 117, 136}, {118, 122, 69}, },
            {{48, 109, -28}, {110, 110, 137}, {111, 122, 69}, },
            {{48, 107, -32}, {108, 108, 138}, {109, 122, 69}, },
            {{48, 100, -33}, {101, 101, 139}, {102, 122, 69}, },
            {{48, 90, -26}, {97, 97, 140}, {98, 122, 69}, },
            {{48, 100, -33}, {101, 101, 141}, {102, 122, 69}, },
            {{48, 114, -75}, {115, 115, 142}, {116, 122, 69}, },
            {{48, 90, -26}, {97, 97, 143}, {98, 122, 69}, },
            {{48, 100, -33}, {101, 101, 144}, {102, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 116, -29}, {117, 117, 145}, {118, 122, 69}, },
            {{48, 104, -30}, {105, 105, 146}, {106, 122, 69}, },
            {{48, 115, -45}, {116, 116, 147}, {117, 122, 69}, },
            {{48, 100, -33}, {101, 101, 148}, {102, 122, 69}, },
            {{48, 100, -33}, {101, 101, 149}, {102, 122, 69}, },
            {{48, 99, -73}, {100, 100, 150}, {101, 122, 69}, },
            {{48, 107, -32}, {108, 108, 151}, {109, 122, 69}, },
            {},
            {{48, 122, -26}, },
            {{48, 110, -31}, {111, 111, 152}, {112, 122, 69}, },
            {{48, 115, -45}, {116, 116, 153}, {117, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 114, -75}, {115, 115, 154}, {116, 122, 69}, },
            {{48, 100, -33}, {101, 101, 155}, {102, 122, 69}, },
            {{48, 90, -26}, {97, 97, 156}, {98, 122, 69}, },
            {{48, 104, -30}, {105, 105, 157}, {106, 122, 69}, },
            {{48, 111, -95}, {112, 112, 158}, {113, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 116, -29}, {117, 117, 159}, {118, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 100, -33}, {101, 101, 160}, {102, 122, 69}, },
            {{48, 115, -45}, {116, 116, 161}, {117, 122, 69}, },
            {{48, 90, -26}, {97, 97, 162}, {98, 122, 69}, },
            {{48, 113, -46}, {114, 114, 163}, {115, 122, 69}, },
            {{48, 109, -28}, {110, 110, 164}, {111, 122, 69}, },
            {{48, 98, -106}, {99, 99, 165}, {100, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 110, -31}, {111, 111, 166}, {112, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 100, -33}, {101, 101, 167}, {102, 122, 69}, },
            {{48, 109, -28}, {110, 110, 168}, {111, 122, 69}, },
            {{48, 104, -30}, {105, 105, 169}, {106, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 113, -46}, {114, 114, 170}, {115, 122, 69}, },
            {{48, 115, -45}, {116, 116, 171}, {117, 122, 69}, },
            {{48, 98, -106}, {99, 99, 172}, {100, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 107, -32}, {108, 108, 173}, {109, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 98, -106}, {99, 99, 174}, {100, 122, 69}, },
            {{48, 109, -28}, {110, 110, 175}, {111, 122, 69}, },
            {{48, 90, -26}, {97, 102, 69}, {103, 103, 176}, {104, 122, 69}, },
            {{48, 103, -48}, {104, 104, 177}, {105, 122, 69}, },
            {{48, 101, -43}, {102, 102, 178}, {103, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 99, -73}, {100, 100, 179}, {101, 122, 69}, },
            {{48, 110, -31}, {111, 111, 180}, {112, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 100, -33}, {101, 101, 181}, {102, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 115, -45}, {116, 116, 182}, {117, 122, 69}, },
            {{48, 103, -48}, {104, 104, 183}, {105, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 104, -30}, {105, 105, 184}, {106, 122, 69}, },
            {{48, 109, -28}, {110, 110, 185}, {111, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 115, -45}, {116, 116, 186}, {117, 122, 69}, },
            {{48, 122, -26}, },
            {{48, 104, -30}, {105, 105, 187}, {106, 122, 69}, },
            {{48, 110, -31}, {111, 111, 188}, {112, 122, 69}, },
            {{48, 109, -28}, {110, 110, 189}, {111, 122, 69}, },
            {{48, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {6, 0, 0, 0, 0, -1, 5, -1, -1, 13, 14, 5, 4, 20, 4, 21, 5, 6, 6, 32, 26, 10, 11, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 23, 24, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 15, -1, 16, 0, 12, 11, 9, 11, -1, 8, 11, 11, 11, -1, 11, 7, 6, 10, 12, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 11, 9, -1, 2, 2, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
